// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatProcessBytes(arg1) {
  return window['go']['main']['App']['FormatProcessBytes'](arg1);
}

export function GetAllProcesses() {
  return window['go']['main']['App']['GetAllProcesses']();
}

export function GetCPUDetails() {
  return window['go']['main']['App']['GetCPUDetails']();
}

export function GetCPUHistory(arg1) {
  return window['go']['main']['App']['GetCPUHistory'](arg1);
}

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetDiskDetails() {
  return window['go']['main']['App']['GetDiskDetails']();
}

export function GetDiskHistory(arg1) {
  return window['go']['main']['App']['GetDiskHistory'](arg1);
}

export function GetDiskInfo() {
  return window['go']['main']['App']['GetDiskInfo']();
}

export function GetDockerHistory(arg1) {
  return window['go']['main']['App']['GetDockerHistory'](arg1);
}

export function GetDockerMetrics() {
  return window['go']['main']['App']['GetDockerMetrics']();
}

export function GetDockerStatus() {
  return window['go']['main']['App']['GetDockerStatus']();
}

export function GetNetworkHistory(arg1) {
  return window['go']['main']['App']['GetNetworkHistory'](arg1);
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetRAMDetails() {
  return window['go']['main']['App']['GetRAMDetails']();
}

export function GetRAMHistory(arg1) {
  return window['go']['main']['App']['GetRAMHistory'](arg1);
}

export function GetRAMInfo() {
  return window['go']['main']['App']['GetRAMInfo']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function SearchProcessesByPort(arg1) {
  return window['go']['main']['App']['SearchProcessesByPort'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
