// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';
import {history} from '../models';
import {docker} from '../models';
import {network} from '../models';

export function FormatProcessBytes(arg1:number):Promise<string>;

export function GetAllProcesses():Promise<Array<process.ProcessWithPorts>>;

export function GetCPUDetails():Promise<string>;

export function GetCPUHistory(arg1:number):Promise<Array<history.TimeSeriesPoint>>;

export function GetCPUInfo():Promise<string>;

export function GetDiskDetails():Promise<string>;

export function GetDiskHistory(arg1:number):Promise<Array<history.TimeSeriesPoint>>;

export function GetDiskInfo():Promise<string>;

export function GetDockerHistory(arg1:number):Promise<Array<history.DockerMetrics>>;

export function GetDockerMetrics():Promise<docker.Metrics>;

export function GetDockerStatus():Promise<docker.Status>;

export function GetNetworkHistory(arg1:number):Promise<Array<history.NetworkMetrics>>;

export function GetNetworkStatus():Promise<network.Status>;

export function GetRAMDetails():Promise<string>;

export function GetRAMHistory(arg1:number):Promise<Array<history.TimeSeriesPoint>>;

export function GetRAMInfo():Promise<string>;

export function KillProcess(arg1:number):Promise<void>;

export function SearchProcessesByPort(arg1:number):Promise<Array<process.ProcessWithPorts>>;

export function Shutdown():Promise<void>;
