// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUDetails():Promise<string>;

export function GetCPUInfo():Promise<string>;

export function GetDiskDetails():Promise<string>;

export function GetDiskInfo():Promise<string>;

export function GetRAMDetails():Promise<string>;

export function GetRAMInfo():Promise<string>;
