// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDatabase(arg1) {
  return window['go']['main']['App']['AddDatabase'](arg1);
}

export function AddGitRepo(arg1) {
  return window['go']['main']['App']['AddGitRepo'](arg1);
}

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function DisconnectDatabase(arg1) {
  return window['go']['main']['App']['DisconnectDatabase'](arg1);
}

export function FormatProcessBytes(arg1) {
  return window['go']['main']['App']['FormatProcessBytes'](arg1);
}

export function GetAllDatabases() {
  return window['go']['main']['App']['GetAllDatabases']();
}

export function GetAllGitRepos() {
  return window['go']['main']['App']['GetAllGitRepos']();
}

export function GetAllProcesses() {
  return window['go']['main']['App']['GetAllProcesses']();
}

export function GetAllServers() {
  return window['go']['main']['App']['GetAllServers']();
}

export function GetCPUDetails() {
  return window['go']['main']['App']['GetCPUDetails']();
}

export function GetCPUHistory(arg1) {
  return window['go']['main']['App']['GetCPUHistory'](arg1);
}

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetDiskDetails() {
  return window['go']['main']['App']['GetDiskDetails']();
}

export function GetDiskHistory(arg1) {
  return window['go']['main']['App']['GetDiskHistory'](arg1);
}

export function GetDiskInfo() {
  return window['go']['main']['App']['GetDiskInfo']();
}

export function GetDockerHistory(arg1) {
  return window['go']['main']['App']['GetDockerHistory'](arg1);
}

export function GetDockerMetrics() {
  return window['go']['main']['App']['GetDockerMetrics']();
}

export function GetDockerStatus() {
  return window['go']['main']['App']['GetDockerStatus']();
}

export function GetGitRepoChanges(arg1) {
  return window['go']['main']['App']['GetGitRepoChanges'](arg1);
}

export function GetNetworkHistory(arg1) {
  return window['go']['main']['App']['GetNetworkHistory'](arg1);
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetRAMDetails() {
  return window['go']['main']['App']['GetRAMDetails']();
}

export function GetRAMHistory(arg1) {
  return window['go']['main']['App']['GetRAMHistory'](arg1);
}

export function GetRAMInfo() {
  return window['go']['main']['App']['GetRAMInfo']();
}

export function GetSavedAPIRequests() {
  return window['go']['main']['App']['GetSavedAPIRequests']();
}

export function GetTopCPUProcesses() {
  return window['go']['main']['App']['GetTopCPUProcesses']();
}

export function GetTopDiskProcesses() {
  return window['go']['main']['App']['GetTopDiskProcesses']();
}

export function GetTopMemoryProcesses() {
  return window['go']['main']['App']['GetTopMemoryProcesses']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function OpenFolderPicker() {
  return window['go']['main']['App']['OpenFolderPicker']();
}

export function OpenInVSCode(arg1) {
  return window['go']['main']['App']['OpenInVSCode'](arg1);
}

export function RefreshAllGitRepos() {
  return window['go']['main']['App']['RefreshAllGitRepos']();
}

export function RefreshGitRepo(arg1) {
  return window['go']['main']['App']['RefreshGitRepo'](arg1);
}

export function RemoveDatabase(arg1) {
  return window['go']['main']['App']['RemoveDatabase'](arg1);
}

export function RemoveGitRepo(arg1) {
  return window['go']['main']['App']['RemoveGitRepo'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function SearchProcessesByPort(arg1) {
  return window['go']['main']['App']['SearchProcessesByPort'](arg1);
}

export function SendAPIRequest(arg1) {
  return window['go']['main']['App']['SendAPIRequest'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1);
}
