// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {devtools} from '../models';
import {process} from '../models';
import {history} from '../models';
import {docker} from '../models';
import {network} from '../models';

export function AddDatabase(arg1:devtools.DatabaseInfo):Promise<devtools.DatabaseInfo>;

export function AddGitRepo(arg1:devtools.GitRepoInfo):Promise<devtools.GitRepoInfo>;

export function AddServer(arg1:devtools.ServerInfo):Promise<devtools.ServerInfo>;

export function ConnectDatabase(arg1:string):Promise<devtools.DatabaseInfo>;

export function DisconnectDatabase(arg1:string):Promise<devtools.DatabaseInfo>;

export function FormatProcessBytes(arg1:number):Promise<string>;

export function GetAllDatabases():Promise<Array<devtools.DatabaseInfo>>;

export function GetAllGitRepos():Promise<Array<devtools.GitRepoInfo>>;

export function GetAllProcesses():Promise<Array<process.ProcessWithPorts>>;

export function GetAllServers():Promise<Array<devtools.ServerInfo>>;

export function GetCPUDetails():Promise<string>;

export function GetCPUHistory(arg1:number):Promise<Array<history.TimeSeriesPoint>>;

export function GetCPUInfo():Promise<string>;

export function GetDiskDetails():Promise<string>;

export function GetDiskHistory(arg1:number):Promise<Array<history.TimeSeriesPoint>>;

export function GetDiskInfo():Promise<string>;

export function GetDockerHistory(arg1:number):Promise<Array<history.DockerMetrics>>;

export function GetDockerMetrics():Promise<docker.Metrics>;

export function GetDockerStatus():Promise<docker.Status>;

export function GetGitRepoChanges(arg1:string):Promise<Array<string>>;

export function GetNetworkHistory(arg1:number):Promise<Array<history.NetworkMetrics>>;

export function GetNetworkStatus():Promise<network.Status>;

export function GetRAMDetails():Promise<string>;

export function GetRAMHistory(arg1:number):Promise<Array<history.TimeSeriesPoint>>;

export function GetRAMInfo():Promise<string>;

export function GetSavedAPIRequests():Promise<Array<devtools.APIRequest>>;

export function KillProcess(arg1:number):Promise<void>;

export function OpenFolderPicker():Promise<string>;

export function OpenInVSCode(arg1:string):Promise<void>;

export function RefreshGitRepo(arg1:string):Promise<devtools.GitRepoInfo>;

export function RemoveDatabase(arg1:string):Promise<void>;

export function RemoveGitRepo(arg1:string):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function SearchProcessesByPort(arg1:number):Promise<Array<process.ProcessWithPorts>>;

export function SendAPIRequest(arg1:devtools.APIRequest):Promise<devtools.APIResponse>;

export function Shutdown():Promise<void>;

export function StartServer(arg1:string):Promise<devtools.ServerInfo>;

export function StopServer(arg1:string):Promise<devtools.ServerInfo>;

export function TestDatabaseConnection(arg1:devtools.DatabaseInfo):Promise<boolean|string>;
