// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUDetails() {
  return window['go']['main']['App']['GetCPUDetails']();
}

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetDiskDetails() {
  return window['go']['main']['App']['GetDiskDetails']();
}

export function GetDiskInfo() {
  return window['go']['main']['App']['GetDiskInfo']();
}

export function GetRAMDetails() {
  return window['go']['main']['App']['GetRAMDetails']();
}

export function GetRAMInfo() {
  return window['go']['main']['App']['GetRAMInfo']();
}
